services:
  - type: web
    name: telegram-stream-bot
    env: docker
    plan: free
    numInstances: 1
    port: 8000
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
